export const SPONSORS = [
	{
		id: "logoFunes",
		name: "Alcaldia Municipal de Funes",
		url: "https://www.funes-narino.gov.co/",
		w:`auto`,
		h:`24`,


	},
	{
		id: "jamez",
		name: "Jamez Cundar Zambrano",
		url: "https://www.facebook.com/kike.gomez.5680",
		w:`auto`,
		h:`auto`,
	},
	{
		id: "losPaisitas",
		name: "Corporación Deportiva Los Paisitas de Medellín",
		url: "https://festivaldefestivales.com/",
		w:`auto`,
		h:`24`,
	},
	{
		id: "cauca",
		name: "Electro Créditos del Cauca",
		url: "https://electrocreditosdelcauca.com/",
		w:`auto`,
		h:`auto`,
	},
	{
		id: "Fenix",
		name: "Fénix Fundación",
		url: "https://www.informacolombia.com/directorio-empresas/informacion-empresa/fundacion-social-deportiva-fenix-foundation",
		w:`auto`,
		h:`24`,
	},
	{
		id: "fortaleza",
		name: "Fortaleza Inmobiliaria",
		url: "https://www.facebook.com/oscararmando.futurasestrellas",
		w:`auto`,
		h:`23`,
	},
	{
		id: "Minerales",
		name: "Minerales la Golondrina",
		url: "/",
		w:`auto`,
		h:`24`,
	},
	{
		id: "Sacha",
		name: "Sache Kiwe Vitalidad Ancestral",
		url: "/",
		w:`auto`,
		h:`24`,
	},
	{
		id: "futurasEstrellas",
		name: "Escuela de Fútbol Futuras Estrellas Corporacion Social y Deportiva",
		url: "https://www.facebook.com/oscararmando.futurasestrellas",
		w:`auto`,
		h:`24`,
	},
	{
		id: "alianzaSurena",
		name: "Organización y montaje eventos deportivos, culturales y artisticos Alianza Sureña. ",
		url: "https://www.facebook.com/oscarbolanoscastro",
		w:'auto',
		h:`auto`,
	},
	{
		id: "osbol",
		name: "Osbol Sport Manager",
		url: "https://www.facebook.com/profile.php?id=853397289",
		w:'auto',
		h:`auto`,
	},
	{
		id: "coacremat",
		name: "Coperativa Coacremat",
		url: "https://www.coacremat.coop/",
		w:'auto',
		h:`auto`,
	},
	{
		id: "liganarino",
		name: "Liga de Futbol de Nariño",
		url: "https://www.ligafutbolnarino.com/",
		w:'auto',
		h:`auto`,
	},
] as const